# Generated by Django 4.1.2 on 2024-12-03 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceTracking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_work", models.DateField(auto_now_add=True)),
                ("checkin", models.TimeField(blank=True, null=True)),
                ("checkout", models.TimeField(blank=True, null=True)),
                ("overtime", models.FloatField(blank=True, null=True)),
                ("total_working", models.FloatField(blank=True, null=True)),
                ("is_late", models.BooleanField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("checkin", "Check In"),
                            ("checkout", "Check Out"),
                            ("overtime", "Overtime"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attendance_tracking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.attendancetracking",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
